[package]
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2024"
license = "Apache-2.0"
name = "tests"
version = "0.0.0"
publish = false

[dependencies]
assert_matches = "1.5"

# Dependencies from the `fuel-core` repository:
fuel-core = { workspace = true, default-features = false }
# Using full semver as the workspace Cargo.toml (see the comment there) 
fuel-core-client = { workspace = true, default-features = false }

# Dependencies from the `fuel-vm` repository:
fuel-vm = { workspace = true, features = ["random"] }

# Dependencies from the `fuels-rs` repository:
fuels = { workspace = true }

hex = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
tai64 = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[[test]]
harness = true
name = "integration_tests"
path = "test_projects/harness.rs"

[package.metadata.cargo-udeps.ignore]
normal = [
    "assert_matches",
    "fuel-core",
    "fuel-core-client",
    "fuel-vm",
    "paste",
    "pretty_assertions",
    "rand",
    "sha2",
    "sha3",
    "tai64",
]

[lints.clippy]
# turn clippy off to avoid clippy CI check needing to build test projects
all = "allow"
